name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.35
        # Optional: if set to true then the action will use pre-installed Go
        # skip-go-installation: true
    - name: Get rsrc
      run: go get -u github.com/akavel/rsrc
    - name: Run rsrc
      run: $(go env GOPATH)/bin/rsrc -manifest wdl-version-manager.exe.manifest -o wdl-version-manager.syso
    - name: go mod tidy (this is needed after go get)
      run: go mod tidy
    - name: Build
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -o wdl-version-manager.exe -ldflags="-X main.archiveUser=${ARCHIVE_USER} -X main.archivePass=${ARCHIVE_PASS}"
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: wdl-version-manager.exe
